// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfsmw4kne5mDjSvpmPYk2OCiDQ1sLb-c0',
    appId: '1:34669112744:web:d4088f5ff6cf61472e419d',
    messagingSenderId: '34669112744',
    projectId: 'petanitambak-cf143',
    authDomain: 'petanitambak-cf143.firebaseapp.com',
    storageBucket: 'petanitambak-cf143.appspot.com',
    measurementId: 'G-GK3HP8MDT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXO3k8UHRVksWeFM_rD7refekFt1taG0o',
    appId: '1:34669112744:android:2e8d595eef8a2ca52e419d',
    messagingSenderId: '34669112744',
    projectId: 'petanitambak-cf143',
    storageBucket: 'petanitambak-cf143.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsHtYC-kBUV3PiG8TZRqvL2-T03rdYijg',
    appId: '1:34669112744:ios:317b4adb9131221d2e419d',
    messagingSenderId: '34669112744',
    projectId: 'petanitambak-cf143',
    storageBucket: 'petanitambak-cf143.appspot.com',
    iosClientId: '34669112744-7go2n8d16ud9outjsao8p3dg6d9d3dcm.apps.googleusercontent.com',
    iosBundleId: 'com.example.petaniTambak',
  );
}
